### ISSUE TITLE
Add ref attribute

### ISSUE THREAD

**Issue by guncha** [pixelass/jsx-create-element#3]
This is almost perfect for what I'm looking for, which is something to make it simpler to create a bunch of markup with event handlers and references without having to find the nodes and add handlers directly. Part of it is being able to grab a reference to a node somewhere deep in the tree:

```js
let statusEl

const root = <div>
  ...
  <div ref={ el => statusEl = el } />
  ...
</div>

// statusEl is now set to the nested HTMLElement
```

This is a fairly simple addition and I'm willing to open a PR for it, but the tests are currently broken and idk if the setup you have would allow testing something like this.

**Comment by pixelass** [comment]
@guncha Sorry for the late reply  
I just added a branch https://github.com/pixelass/jsx-create-element/tree/bug/remove-test which you can use to create the PR.
At this small feature-set I will do testing manually and then merge into master.

**Comment by pixelass** [comment]
@guncha keep in mind the syntax above is not correct. You cannot return an assignment `=>{}` is needed

````jsx
let statusEl

const root = <div>
  ...
  <div ref={el => { statusEl = el }} />
  ...
</div>

// statusEl is now set to the nested HTMLElement
````

**Comment by guncha** [comment]
@pixelass I kind of went ahead and created my own library - https://github.com/Pathgather/jsx-render-dom

As for the syntax, I can most certainly return an assignment as it is a valid expression. Maybe you're thinking of variable declaration - that's a statement and you can't do something like `return var x = 5` (this is a mistake in the design of the language, if you ask me).

**Comment by pixelass** [comment]
@guncha my bad about the assginment. Maybe that was React speciffic or assigning `x => this.el = x`. I confirm that my statement was wrong. 
I looked through your repo, nice work.

I never intended to use this module it was just me playing around and actually this snippet does almost the same in 225bytes (minus the eventHandlers)

```js

/** @jsx j*/
const j=(d=>(t,p,...c)=>{const n=d.createElement(t);p&&Object.keys(p).forEach(b=>{const a=p[b];'style'===b?(x=>Object.keys(a).forEach(b=> n.style[b]=a[b]))():n.setAttribute('className'===b?'class':'htmlFor'===b?'for':b,a)});c.forEach(a=>n.appendChild(a[0]?d.createTextNode(a):a));return n})(document)
```
### Prettyprinted

```js
/** @jsx j*/
const j = (d => (t, p, ...c) => {
  const n = d.createElement(t);
  p && Object.keys(p).forEach(b => {
    const a = p[b];
    'style' === b ? (x => Object.keys(a).forEach(b => n.style[b] = a[b]))() : n.setAttribute('className' === b ? 'class' : 'htmlFor' === b ? 'for' : b, a)
  });
  c.forEach(a => n.appendChild(a[0] ? d.createTextNode(a) : a));
  return n
})(document)
```

I like your idea with the `ref` attribute and might actually add it in myself if I ever feel bored. nice suggestion. keeping this open for now
